[package]
name = "mozimc"
version = "0.1.0"
authors = ["Gris Ge <fge@redhat.com>"]
edition = "2018"
description = "CLI tool for mozim(DHCP Client)"

[[bin]]
name = "mozimc"
path = "mozimc.rs"

[dependencies]
mozim = { path = "../lib" }
tokio = { version = "0.3", features = ["full"] }
